############################################################
### CARECONNECT API - GENERAL TESTS
############################################################


############################################################
### Base URL
############################################################

@baseUrl = http://localhost:3000



############################################################
### Root Route
############################################################

GET {{baseUrl}}/



############################################################
### Health Check
############################################################

GET {{baseUrl}}/health



############################################################
### Swagger Documentation
############################################################

GET {{baseUrl}}/api-docs



############################################################
### Database Health Check
############################################################

GET {{baseUrl}}/database-check