############################################################
### CARECONNECT API - USERS
############################################################


############################################################
### Base URL
############################################################

@baseUrl = http://localhost:3000

@userId = 6a7429b3e1791b9229caa5b3



############################################################
### Get All Users
############################################################

GET {{baseUrl}}/api/users



############################################################
### Get User By ID
############################################################

GET {{baseUrl}}/api/users/{{userId}}



############################################################
### Create User
############################################################

POST {{baseUrl}}/api/users
Content-Type: application/json


{
    "firstName": "David",
    "lastName": "Caleb",
    "username": "davidcaleb",
    "email": "david@example.com",
    "password": "Password123!",
    "role": "user"
}



############################################################
### Update User
############################################################

PUT {{baseUrl}}/api/users/{{userId}}
Content-Type: application/json


{
    "firstName": "David Updated"
}



############################################################
### Delete User
############################################################

DELETE {{baseUrl}}/api/users/{{userId}}